plugins {
	id 'java-library'
}

group = 'poiw.project'
version = '0.0.1'
description = 'Card reader utilities for building CAS API client'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(25)
	}
}

repositories {
	mavenCentral()
}

dependencies {
	testImplementation 'org.junit.jupiter:junit-jupiter:6.0.1'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	implementation 'org.bouncycastle:bcpkix-jdk18on:1.78.1'
}

tasks.named('test') {
	useJUnitPlatform()
}

task runDemoUID(type: JavaExec) {
    group = "Execution"
    description = "Runs the demo class"
    classpath = sourceSets.main.runtimeClasspath
    mainClass = 'poiw.project.CAS.demoUID'
}

task runDemoELS(type: JavaExec) {
    group = "Execution"
    description = "Runs the demo class"
    classpath = sourceSets.main.runtimeClasspath
    mainClass = 'poiw.project.CAS.demoELS'
}
